### ISSUE TITLE
Bug number of links in the note freezes app

### ISSUE THREAD

**Issue by dmdymov** [clipto-pro/Android#10]
If you have a note in clipto pro with a huge ammount of links in it app freezes on opening because of previews. After the freeze scrolling is awful.

Xiaomi MI A3, more than a thousand links. 

Maybe it's not a frequent case but other simillar apps usually solve this problem by presenting an option "Disable previews" or even "Disable live links".

Thank you.

**Comment by dmdymov** [comment]
UPD I've found settings for each note. Yes, you can set note as plain text, but I have a note so huge that I can't even open it to change settings. I can export it of course and make some small notes, but it's not very straightforward.

**Comment by atrashler** [comment]
We will add additional setting for 'Note View' screen that will let to change View Style aka in the main list but with specific styles for the note's screen. It will have at least two styles: 'Default' and 'Preview'.
Also for your scenario we will also check the performance issue. Probably it can be solved.

**Comment by atrashler** [comment]
> UPD I've found settings for each note. Yes, you can set note as plain text, but I have a note so huge that I can't even open it to change settings. I can export it of course and make some small notes, but it's not very straightforward.

Is it still actual in the latest build 2.42.5? I have found some issues with links recognition logic (any sequence of words divided with dot was treated as a link).

**Comment by atrashler** [comment]
Have closed due to no response. @dmdymov if you still experience the problem in the latest versions of the app, please let me know and send some example (if it is possible). Thanks!
