### ISSUE TITLE
Just randomly stopped copying notes(Android 12)

### ISSUE THREAD

**Issue by d0x360** [clipto-pro/Android#101]
I know Samsung has insane power savings features in Android but I've disabled all of them, even ones people can't usually disable unless they use adb. 

I've literally been a clipto user since the day it went on the play store so I know my way around the app quite well although I don't usually post here because I always forget it has a GitHub page so I just shoot off an email lol
 
So because of this problem I wanted to make sure I didn't somehow stop getting updates from the store so I checked and noticed the beta branch hadn't been updated since December 2021, good there then.  

So I was curious if anyone was having similar issues (Samsung or not) on Android 12 with the may security update to Android and June update to Google Play itself (if you don't know how to update Play don't hesitate to ask but it updates itself so don't worry.) 

So recently... I'd say maybe starting 2 weeks ago the app isn't copying anything unless I launch it first and make sure to launch it roughly every hour and 115 min to 2 hours. The notification is up and I haven't made any changes to my phone settings nor has any firmware updates been pushed to my phone since clipto stopped working properly.  All I've done so far is clear the app cache, I haven't don't a uninstall/reinstall.

Here's a screenshot of my device info for anyone curious 

![Screenshot_20220707-010336_Settings](https://user-images.githubusercontent.com/14056857/177695488-3cecad4c-a107-4166-8ed5-a3e0c5554729.jpg)

Thanks!

**Comment by niuhongbin1** [comment]
Hi, do you deal with this problem? I use some tools but they are useless. how can i get clipto in anroid 12.

**Comment by d0x360** [comment]
Google play store

**Comment by febryanvaldo** [comment]
Hey, have you found any solution for this...? I'm using Pixel 4XL, Clipto won't automatically copy the clipboard (make a note), so i have to reopen Clipto app to make this work.

**Comment by d0x360** [comment]
Nothing 100% official yet.  Dev is moving so hopefully we can work this all
out when he's settled in.

For now 1 person on Android 10 has managed to get tasker working to keep it
alive but I tried the same and had no luck

**Comment by febryanvaldo** [comment]
Hmmm, okay than... It's just in Android app, the desktop working flawlessfly.

**Comment by d0x360** [comment]
Yeah it's just Android and we aren't sure if it's crashing or being put to
sleep.

Thats something I'm going to try and figure out this week so there is as
much info for him as possible when he is ready to code again.

Either way a watchdog service should take care of it...

**Comment by atrashler** [comment]
As a possible workaround for Android 10+

Place the tile 'Keyboard Companion' into a visible area so it could be
visible in the notification bar.
In such case the app will be resumed by the TilesService and should not be
killed by the system.

**Comment by d0x360** [comment]
> As a possible workaround for Android 10+ Place the tile 'Keyboard Companion' into a visible area so it could be visible in the notification bar. In such case the app will be resumed by the TilesService and should not be killed by the system.
> […](#)
> 

Not a bad idea.   The really odd thing is the notification is still displaying and won't swipe away like it will if the app is closed but the notification didn't clear.

So I'm thinking that it's crashing.  I'm going to try and run it through the android emulator tomorrow. That should tell me something.

**Comment by d0x360** [comment]
So I just noticed something... I pulled down the notification pane because touching anywhere on the notification will open the app.

I just happened to click the little play symbol and Clipto said monitoring of clipboard resumed...  That's another thing to test out.

Let me me know if they happens to anyone else and  check if it starts copying again.  After you hit play it will look like this...

![Screenshot_20220927_040559_Chrome](https://user-images.githubusercontent.com/14056857/192470009-4ba85bbc-e914-4ef2-9065-29820fa70345.jpg)

**Comment by igorzhilin** [comment]
Here's the same issue: https://github.com/clipto-pro/Desktop/issues/148#issuecomment-1405359710

Clipto does not work on 12+ because Android stopped giving the permission READ_LOGS. This permission must now be given every single time you need to access the logs. 

As I understand, clipto on Android worked by capturing the clipboard changes from logcat (Android system log service). Now, it's not possible.

**Comment by d0x360** [comment]
> Here's the same issue: [clipto-pro/Desktop#148 (comment)](https://github.com/clipto-pro/Desktop/issues/148#issuecomment-1405359710)
> 
> Clipto does not work on 12+ because Android stopped giving the permission READ_LOGS. This permission must now be given every single time you need to access the logs.
> 
> As I understand, clipto on Android worked by capturing the clipboard changes from logcat (Android system log service). Now, it's not possible.


I'll have to look into that too then.  It's the main issue I want to tackle but I've been VERY sick for the past 4ish months so progress has been slow but there is finally some light at the end of this horrible tunnel.

Ive heard about apps that need usage access and how unchecking it then rechecking it will have the app working again but the issue with that being the solution is when you enable usage access it would launch the app receivers in the background anyways so that would solve for the app crashing or being put to sleep.

Personally I don't have to give permission to anything clipto related for it to work, but if it's been around 30 min since I've used it or copied anything then I'll have to launch the app to wake it.

Ive already written 3 different functions that would bring the app back to life if it crashed or was put to sleep... Samsung is notorious for putting apps to sleep regardless of settings and that's on top of androids own sleep settings which Samsung hides so the app is being put to sleep no matter what on anything Samsung made after android 10.

That said I setup a few different phones for emulation with clipto installed and all running android 11, 12, and 13 plus detailed logcat

I just haven't had the time to sit and do it.  I'll merge this with the other topic or have Alex merge it.  Rest assured it will be fixed.
