### ISSUE TITLE
JavaScript error - uncaught exception - net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by davidpluseipi** [clipto-pro/Android#14]
Hi, 

I really love clipto! It's my new way to gather notes and copy/paste stuff between my Linux machine running Elementary OS (5.1 Hera; Ubuntu 18.04.3 LTS bionic) and my Pixel 4 (no issues on the android side). 

I downloaded the .AppImage and run that to open clipto, but when I do I get an error from clipto that says 'A JavaScript error occurred in the main process Uncaught Exception: Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE'. 

I just select OK, and so far haven't run into the issue this error is reporting. I am logged into my account on my laptop and phone and seem to be using all the features successfully, but I wanted to report the error regardless.

**Comment by atrashler** [comment]
Will try to reproduce it. Have not seen it before. Thanks!

**Comment by atrashler** [comment]
Should be fixed in the latest update.
Please check in version https://github.com/clipto-pro/Desktop/releases/tag/v1.8.1
Thanks!

**Comment by atrashler** [comment]
fixed in v1.8.1
