### ISSUE TITLE
[Feature Request] Import from Clip Stack

### ISSUE THREAD

**Issue by Dtrieb** [clipto-pro/Android#16]
Import from Clip Stack

[https://play.google.com/store/apps/details?id=com.catchingnow.tinyclipboardmanager](https://play.google.com/store/apps/details?id=com.catchingnow.tinyclipboardmanager) 

would be great.

**Comment by GitAlexToTheGreek** [comment]
Echoing the Clip Stack import request. 🙂

**Comment by atrashler** [comment]
> Echoing the Clip Stack import request. 🙂

ok. will add it in the next release

**Comment by Dtrieb** [comment]
Try it in the new version, didn't work for me.

**Comment by atrashler** [comment]
What version have you used?

**Comment by Dtrieb** [comment]
Clipto Pro 2.39.10
Clip Stack 1.9.8. (build 98)

**Comment by atrashler** [comment]
Strange. Need to investigate it first. Probably some specific case is not covered by our implementation. As workaround it is possible to activate ‘Notes from Clipboard’, switch to Clip Stack and copy every note so Clipto can take this notes as changes from the clipboard.

**Comment by Dtrieb** [comment]
Any news here?

**Comment by atrashler** [comment]
> Any news here?

Just wanted to write you also:) Have you checked it in the latest release (2.41.2) if it works or not? I have updated the logic of import. If not, then I will create another build with some logic that will help to determine the problem and not to provide your backup to me (seems like your backup has some structure that Clipto does not expect to parse)

**Comment by Dtrieb** [comment]
I install both Apps on another device and try it there.
Didn't work also.

So I upload you the Testfile (I made from Clip Stack)
[Clip Stack Backup So., Feb. 23 18-22-37.txt](https://github.com/clipto-pro/Android/files/4241885/Clip.Stack.Backup.So.Feb.23.18-22-37.txt)

**Comment by atrashler** [comment]
This example works.

![clip_stack](https://user-images.githubusercontent.com/20585947/75117057-ec5f0000-5676-11ea-9251-8a7087c90015.png)

**Comment by Dtrieb** [comment]
Crazy then i make something, wrong ???
On my other device it didn't work.

**Comment by Dtrieb** [comment]
![photo5951573827911791148](https://user-images.githubusercontent.com/3650284/75117190-a3f01400-566f-11ea-9723-c73ecf6e616e.jpg)

**Comment by atrashler** [comment]
OMG.. could you change the locale to English and try again? I suppose it should work after that.
Anyway I will fix the issue in the next release:)

**Comment by Dtrieb** [comment]
Yes if I change the locale to English it works!  👍

**Comment by atrashler** [comment]
fixed in https://github.com/clipto-pro/Android/releases/tag/v2.41.3
