### ISSUE TITLE
Adding photo from camera

### ISSUE THREAD

**Issue by jab888** [clipto-pro/Android#17]
Adding photo directly from the camera app in Android doesn't work. 
You need to select file in order to add a photo.
![Screenshot_2020-01-25-15-46-05-21_d71d70e3cd55e8de213422a3784df2f0](https://user-images.githubusercontent.com/60093292/73122862-d7b11e80-3f89-11ea-91ad-17a1ce428dec.png)

**Comment by atrashler** [comment]
Could you write your phone info (model and android version)?

Also if it possible, could you make a video of how it looks?

**Comment by jab888** [comment]
![Screenshot_2020-01-25-15-53-19-04](https://user-images.githubusercontent.com/60093292/73123090-252e8b00-3f8c-11ea-998b-dbba41cfb950.png)

https://drive.google.com/file/d/18xgg0iFWAQTYgs8_eoNSy07EAQr3yP9I/view?usp=drivesdk
