### ISSUE TITLE
Doesn't create notes from clipboard

### ISSUE THREAD

**Issue by hotigris** [clipto-pro/Android#22]
Sometimes the Android app doesn't create notes from clipboard. Interesting thing is that it catches text from the clipboard of another connected device (a laptop), but seems to be unable to do the same with the phone's own clipboard. It is a Huawei P Smart, Android 10. Thank you for any help!

**Comment by atrashler** [comment]
On Android 10 to take notes from clipboard you need to use our alternative solutions or configure the app via adb. Please check for instructions in the app (available in latest version on Google Play)

**Comment by hotigris** [comment]
Hi, Alex,
thank you, I got it.
Imre

**Comment by atrashler** [comment]
you are welcome:)
