### ISSUE TITLE
no sync with Linux AppImage

### ISSUE THREAD

**Issue by 1stFox** [clipto-pro/Android#23]
I signed in and out, multiple times, with the same email and I did so over a period of a week in case you were having issues with you cloud. But finally I lost all my notes because I wanted to try logging in with Google hoping the tokens would make a difference. No luck yet, here's to keeping my fingers crossed. I really do love the app.

**Comment by atrashler** [comment]
Could you try to re-open the app again (probably with sign out / sign in)

It was slightly stupid problem of mine and now the app should work:)

Thanks!

**Comment by atrashler** [comment]
The problem is solved on the server side. Not an issue of a build
