### ISSUE TITLE
Share with clipto issues

### ISSUE THREAD

**Issue by nathanfilz** [clipto-pro/Android#24]
I am experiencing issues when attempting to use the built in share feature in Chrome on my Android device. 
Instead of sending a link to the site I am sharing, ie https://github.com/clipto-pro/,  I get a funky com.google.Chrome.***** attachment and that's it. ![Screenshot_20200324-001206](https://user-images.githubusercontent.com/31555070/77396378-4aabfb00-6d69-11ea-9016-cd7836c838a6.png)

The same thing also happens when I try to append it to an existing note that contains other links. 
![Screenshot_20200324-005152](https://user-images.githubusercontent.com/31555070/77396674-c27a2580-6d69-11ea-8fb5-e502c6db0357.png)

When I share to Keep and Pocket though, it works, so I don't think the feature is broken all around.

Chrome 80.0.3987.149
Android 7.1.1 Moto E (4)Build/NDQS26.69-64-11-16

Am I doing something to screw this up. I swear it used to work.

Sorry for all the edits, struggling with everything it seems tonight.

**Comment by atrashler** [comment]
Could you please attach a screenshot how it looks when you share to Clipto?

**Comment by nathanfilz** [comment]
Here is a step by step screenshot of the process. 
On this page, I click my menu in the upper right hand corner of chrome and click on share.

![Screenshot_20200324-114917](https://user-images.githubusercontent.com/31555070/77459709-c176e180-6dc5-11ea-8a5a-19c3b1630847.png)

I select clipto as the desired target application. 

![Screenshot_20200324-114934](https://user-images.githubusercontent.com/31555070/77459842-eb300880-6dc5-11ea-8a27-e2044577301e.png)

When I go to clipto, this is what was created (from the list view)
![Screenshot_20200324-115415](https://user-images.githubusercontent.com/31555070/77460162-5c6fbb80-6dc6-11ea-8d70-2f3aa41405cc.png)

And finally this is what i see if i open it up.
![Screenshot_20200324-115420](https://user-images.githubusercontent.com/31555070/77460252-76110300-6dc6-11ea-9cd1-9458d73b04d3.png)

**Comment by atrashler** [comment]
Will be fixed in the next release

**Comment by atrashler** [comment]
fixed in 2.44.6
