### ISSUE TITLE
Inconsistent click area for the notes 🐞

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [clipto-pro/Android#27]
Clicking the text doesn't open the note. It's much better explained with a screenshot: 
![Screenshot_20200408-143756~3](https://user-images.githubusercontent.com/9111191/78780813-e19ec700-79a7-11ea-9a28-73c7e8d0bb00.png)

I can open the notes clicking the green area but not the red area. 

Wanna click the red area! ᕙ( ¤ 〰 ¤ )ᕗ

**Comment by atrashler** [comment]
Bug. Thanks!

**Comment by atrashler** [comment]
fixed in 2.44.6
