### ISSUE TITLE
New functions

### ISSUE THREAD

**Issue by AndreAugustoDev** [clipto-pro/Android#28]
1. Recent notes function
Add alternative option when clicking on the notification, display a list of the last copies to select one of them
2. New configuration
Add option to hide the icon in the status bar

**Comment by salman-q** [comment]
You can hide the icon in the status bar if you make the persistent notification to "Other" rather than being "Important". It will also keep the Notification packed in itself.

**Comment by atrashler** [comment]
1) have you checked the existing styles of notification. One of the displays clipboard history (or recent notes)
3) will check it, but I have read that android policy does not recommend to do it because it can be a reason to delete the app from Google Play (but need to check it first)

**Comment by AndreAugustoDev** [comment]
Thank you very much for the tips, I managed to do what I asked, I love your app, the best I found in your role.
Continue with this beautiful work!
