### ISSUE TITLE
bring back pull to refresh option

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Android#30]
what is the reason you removed pull to refresh option?
data not syncing sometimes. please bring back this option.
don't you want client satisfaction or what?
if something is wrong with your socket/FCM then I have to force close the app and open again to resync data. tedious.

please add pull to refresh option

**Comment by atrashler** [comment]
This option was never implemented in the app:)
I will check how it possible to bypass the problem in the regions with unstable internet.

**Comment by atrashler** [comment]
By the way, in account settings (Settings -> Account) it is possible to disable and enable synchronisation. Technically it will force the app to disconnect and connect again to the server. But in case of the problem with unstable internet connection or some transport level errors it also will not help. The problem that you have mentioned need to be investigated. But could you please provide some additional details:
1) Does the problem occur on Android only or Desktop also?
2) How often it occurs
3) The problem occurs while you actively using the app (when it in foreground) or when you bring the app from background to foreground after a long time of inactivity (please write some more details if you have found some stable pattern how it can be reproduced)?
4) Do you use VPN

**Comment by tahsinature** [comment]
I did it.... turning off and on account sync.
But you know, it's still tedious...
yes I'm using VPN.
But i tried turning off VPN also

**Comment by atrashler** [comment]
> I did it.... turning off and on account sync.
> But you know, it's still tedious...
> yes I'm using VPN.
> But i tried turning off VPN also

Actually this setting is not for the scenario that you have described. And it does not guarantee to work in such scenarios as yours (At least I did not test it in such scenario)

VPN is not the cause of the problem. I have just asked to understand your environment to reproduce it. Could you please provide more information for all 4 questions that I have asked previously?

**Comment by atrashler** [comment]
Pull to refresh is not useful for the underlined technology. Have improved the logic of 'Automatically sync notes' so it should work better
