### ISSUE TITLE
Getting duplicates 

### ISSUE THREAD

**Issue by anti-pencil** [clipto-pro/Android#34]
Android 10 - Galaxy S10+. I'm getting duplicates on some notes I've been working on recently. I have the client installed on my Linux box too. They are synchronized. One of the duplicates seems to be an older copy, and one seems to be recent and correct (I hope). No way to tell for sure. Any advice?

**Comment by atrashler** [comment]
The app should not let to create duplicates.
However if the same note created on two different devices (while app is offline) and then get synced across the devices, then it is possible to get both notes.

The questions:
1) the duplicates are visible on both Android and Desktop versions? (if you have Desktop version installed)
2) you see the same number of notes on all your devices?
3) you get changes instantly across all your devices if you create a new note on any of them?
4) how many notes you keep in sync

**Comment by anti-pencil** [comment]
Hi, thank you for the reply. It seems that I had uninstalled clipto on my PC when I went to check for duplicates on my PC. It is only installed on my phone. Now I discover that I lost an addition that I had made to a note. Its quite difficult to swallow losing what I lost. How am I supposed to use the app if I have to worry about this type of issue? Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alex Trashler <notifications@github.com> Date: 2020-06-22  1:20 a.m.  (GMT-06:00) To: clipto-pro/Android <Android@noreply.github.com> Cc: anti-pencil <defrenchguy@gmail.com>, Author <author@noreply.github.com> Subject: Re: [clipto-pro/Android] Getting duplicates  (#34) 
The app should not let to create duplicates.
However if the same note created on two different devices (while app is offline) and then get synced across the devices, then it is possible to get both notes.
The questions:

the duplicates are visible on both Android and Desktop versions? (if you have Desktop version installed)
you see the same number of notes on all your devices?
you get changes instantly across all your devices if you create a new note on any of them?
how many notes you keep in sync


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/clipto-pro/Android/issues/34#issuecomment-647335237",
"url": "https://github.com/clipto-pro/Android/issues/34#issuecomment-647335237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by atrashler** [comment]
You should not experience such kind of issues. But if you get it, then I need to investigate to understand what has happened.

**Comment by atrashler** [comment]
Could you please send me details that I have asked you earlier? (it will help me to understand the cause if the issue)

**Comment by atrashler** [comment]
Have closed due to no response.
