### ISSUE TITLE
Orientation Change with Markdown Table

### ISSUE THREAD

**Issue by inkstain** [clipto-pro/Android#35]
I am finding that when changing orientation from Portrait to Landscape when viewing a Markdown note with a relatively wide table the table width stays the same in Landscape rather than taking advantage of the increase in horizontal space as word-wrapped text does.

When going from Landscape to Portrait it does however narrow down the overall width of the table as it should.

I am on Android 8.1.0 running on a Blackberry KeyOne

Please let me know if there are any questions or if additional info is needed.

Thx for the great app! :)

**Comment by atrashler** [comment]
Have reproduced it. Marked as a bug:) Thanks!

**Comment by atrashler** [comment]
Please check it in the latest version on Google Play (3.4.1) - will be available soon in Beta channel.

**Comment by atrashler** [comment]
Should be fixed in the latest version (4.1.x)
