### ISSUE TITLE
Remembering last "Text type" option

### ISSUE THREAD

**Issue by Mark-Joy** [clipto-pro/Android#39]
Is there a way for app to remember last "Text type" option when creating a new note? For example, I prefer "Text with copied token" but everytime I create a new note, it's either "plain text" or "Text with Links".
This option would surely help.

**Comment by atrashler** [comment]
It will be added. Probably in the next functional update (3.3.0)

**Comment by atrashler** [comment]
fixed in v3.3.1 (will be available in Beta channel soon). The last manually changed text type of any of notes will be used as a default for all new manually created notes.
