### ISSUE TITLE
Clipboard monitoring is active and working even though it is disabled in Settings

### ISSUE THREAD

**Issue by inkstain** [clipto-pro/Android#40]
Found that copying something to the clipboard in another app causes that contents to go to a new note, even though Clipboard Monitoring is disabled. Noticed this on 3.1.6 but it is continuing on 3.2.1. Tried the following to resolve without success

1. Enabled and then disabled Clipboard Monitoring
2. Force stopped the app within Phone App settings and restarted.
3. Rebooted phone
4. Force stopped the app, cleared cache, cleared data, uninstalled and reinstalled 3.2.1
5. Did the optimization when prompted after logging into the app

Thx!

## Android Version Info

Clipto Version: 3.2.1

Android Version: 8.1.0

Hardware: Blackberry KeyOne

**Comment by atrashler** [comment]
It happens for every note you copy while Clipto is in background? Or just an active note in the clipboard? I have added some 'experimental behaviour' for the latest active note in the clipboard. Just to get a feedback:)

**Comment by inkstain** [comment]
Very strange, now it is not doing it as before. After I noticed one copy paste in other apps landing as a note (non-sync) in Clipto, I did the following steps to further verify the issue before starting the ticket

1) going into Pinkt (Pinboard app) and going into its browser and copy a paragraph. Entered into clipboard and found it there. Went into settings to verify that Clipboard Monitoring was disabled (I think I toggled it on and off at this point).

2) Went into my normal web browser and copied some phrase, went into Clipto and verified it was there as a non-sync note. Deleted the unintended notes.

3.) Went into another clipboard app that I have been using for years (Clipboard Actions) and copied one of the previous test clipboard copies, and went back into Clipto and it was in there as again as a non-sync note.

I have now retried all three of these (also force stopping Clipto after step 1) in case it is randomly occuring depending on app launch but I have not been able to reproduce. I should add that while the inadvertent copies to note were happening I did not see the notification indicator that appears when you actually do enable the Clipboard Monitoring.

For sure it was doing it after the clear data, cache and app and relogging in. Don't know what to say aside from "I'll keep an eye out for it again". Let me know if there is anything else that comes to mind from your side.

thx!

**Comment by atrashler** [comment]
The current behavior of this experimental feature is:
1) whenever you navigate to Clipto, it take current text from the clipboard and create a note in app, but does not put it in sync automatically (probably you have copied some password and do not want it to be shared across devices)
2) this experimental feature does not depend on any setting in application settings

Probably this feature is not obvious and should be disabled:) I will turn it off globally.

**Comment by atrashler** [comment]
ok. have turned it off. need to clear the application cache to take effect of this change.

**Comment by inkstain** [comment]
done, thx!. Will let you know if I see it again, but out of curiousity (if I may) what would be different from that experimental feature versus the Clipboard Monitoring feature?



‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by atrashler** [comment]
it could not happen again without my knowledge  about it:) This behaviour is controllable by the app.

Experimental feature - is any new functionality that I add into the app to collect feedback about it. Based on this feedback I could decide if this feature is useful or not and turn it off if it is not.

This feature is turned off by default and will be improved to depend on the state of a setting “Notes from Clipboard”. In such case it will be more understandable.

Actually this feature should work only if “Notes from Clipboard” is activated. It was added for the owners of Android Q who do not want to use one of our current alternatives “how to take notes from clipboard” and prefer navigate back to Clipto each time he changes the clipboard and wants to save it as a new clip.

**Comment by atrashler** [comment]
fixed in v3.3.1 (will be available in Beta channel soon). Should take the current clip from clipboard only if 'Notes from Clipboard' is activated (useful on Android Q).
