### ISSUE TITLE
Scroll bar visual enhancement

### ISSUE THREAD

**Issue by salman-q** [clipto-pro/Android#42]
![Screenshot_20200705-153204__01](https://user-images.githubusercontent.com/67760072/86530357-c6275780-bed5-11ea-980b-da207eb6c587.jpg)

The scroll bar on the right looks very big and ugly. It would be nice to make it a bit sleek. The style shouldn't be too hard to find. Keep the rounded corner. Just make it a bit thinner.

Also, the rendered bullet dots look very big. You can perhaps try to slim them down a bit too.

**Comment by atrashler** [comment]
fixed in v3.3.1 (will be available in Beta channel soon). Slightly made it thinner. Please check in Beta channel
