### ISSUE TITLE
Weird behavior of Recycle Bin

### ISSUE THREAD

**Issue by salman-q** [clipto-pro/Android#45]
![Screenshot_20200705-195432](https://user-images.githubusercontent.com/67760072/86535538-a8221d00-befe-11ea-8bb7-e02c99a2de98.jpg)

When I copy the note from the recycle bin, the note moves to the main list. Is this behavior also intended? I think it would be much intuitive if the note remains in Recycle Bin when I copy the note. This is an unexpected result when the action performed had an entirely different motive.

Edit: Figured out the previous edit.

**Comment by atrashler** [comment]
Actually the more correct behaviour is in the Web and Desktop apps:

1) from the list you can only restore any note and it should not have Copy action

But this behaviour is correct: if you copy a note while the “notes from clipboard” is activated or any other case, then this note is treated as “recently used” and move out the recycle bin.

**Comment by salman-q** [comment]
I see. Doubt cleared.

**Comment by atrashler** [comment]
fixed in v3.3.1 (will be available in Beta channel soon)
