### ISSUE TITLE
Subscription not activated in app

### ISSUE THREAD

**Issue by sunnykatiyar50** [clipto-pro/Android#47]
I hav bought monthly subscription for 5000+ notes. Balance is deducted and Subscription is activated in playstore. It says to open app before 22nd july, I opened the app from the given link, it is still showing free in app. I have also tried relogin, force close aplp and restart etc. Not solved

**Comment by atrashler** [comment]
Will check it and give more details. Now please make sure that:
1) your subscription is activated (go to Gogle Play -> Subscriptions -> Find subscription on Clipto)
2) you have not canceled it after its activation
3) send your account id (Settings -> Scroll down -> Click on Email button -> Send me user_id value in the created email) so I can check what has happened with your subscription (the app checks sku details on server so it could have more actual information about subscription state)?

**Comment by atrashler** [comment]
Could you check the issue and update its status? Thanks!

**Comment by sunnykatiyar50** [comment]
Yeah it is solved now.

**Comment by sunnykatiyar50** [comment]
My Subscription was cancelled yesterday automatically. I mean it totally dissapaeared from subscription section in playstore and app itself. Can you please look into it

**Comment by atrashler** [comment]
> My Subscription was cancelled yesterday automatically. I mean it totally dissapaeared from subscription section in playstore and app itself. Can you please look into it

Could you send me your account id (Settings -> Scroll down -> Click on Email button -> user_id).
If it is disappeared from the Google Play subscription panel then probably it has been canceled by some reason (cancelation, no charge, etc). I need to check it, but I could do it by having your account id. Thanks!

**Comment by sunnykatiyar50** [comment]
sunnykatiyar50@gmail.com

**Comment by sunnykatiyar50** [comment]
sunnykatiyar50@gmail.com

I used this email in clipto as well as playstore for subscription.

**Comment by atrashler** [comment]
Have checked. Your subscription has been canceled by the system (Google Play) because of a billing problem (Google could not access your payment card by some reasons and canceled it). After that the app has checked the expiration date of the last payment period (it was valid until July 2020 05:00) and updated the state of your plan in the app.
If you would like to restore the subscription then now it is only possible by subscribing again because the previous subscription has been fully canceled (if it is disappeared from Google Play -> Subscriptions)

**Comment by sunnykatiyar50** [comment]
Thanx.  I dont know why it was cancelled as payment was upfront from google play balance. Although it was returned after cancellation. So I have subscribed again.
