### ISSUE TITLE
missing "Clear" button on phone app

### ISSUE THREAD

**Issue by coachsequoia** [clipto-pro/Android#48]
I use the Clipto Android app on my Chromebook and phone [Samsung A50].
On Chromebook there is a Clear button on the lower right; it's missing on the phone app. I've tried re-installing the phone app: same issue :{
Also please make it simpler to report issues. I'm a plain ole user, not a geek :} This took way too much time to get to this point.
Thanks!

**Comment by atrashler** [comment]
Could you make a photo how it looks on your device? Also please write the app version. Thanks!

**Comment by atrashler** [comment]
Also. To report an issue from the app it is possible to send an email:)

**Comment by atrashler** [comment]
Closed due to no response. Please send me a photo via email how it looks in the latest version (4.1.x). Thanks!

**Comment by coachsequoia** [comment]
Hi Alex,
I've searched https://github.com/clipto-pro/Android/issues in vain for an
answer to my simple question about Android Clipto app: *how can I
bulk-delete all non-starred entries.* The app seems to show a delete icon
at some seemingly random times and at other times I cannot make the icon
appear except for single entries, of which I have hundreds.
I hope you can answer in lay-person's language.
Thanks!
*sequoia*
*Sequoia Lundy*


*Vancouver:   778-822-4408 toll-free:       877-822-0844US:
 360-436-6444*

**Comment by atrashler** [comment]
Will try to answer (if it will not help, please contact me via email, it will be easier for both of us to use an email:).

To delete all not starred items:

Solution 1 - if you are using the functionality Notes from Clipboard:
1) long tap on a category “Notes from clipboard”
2) click on the top right action in the opened popup
3) confirm the action

Solution 2 - any scenario
1) long tap on any note you want to delete
2) in the appeared context menu select all notes you want to delete
3) confirm your action

Waiting for your reply on email clipto.pro@gmail.com

**Comment by coachsequoia** [comment]
Thanks atrashler 
Am just getting back to trying to clear this app of all my old clips.
Your Solution 1 does not work on my Chromebook.
Solution 2 does.
Thanks!
Cheers
sequoia

**Comment by atrashler** [comment]
Could you please send me a screenshot how it looks when you follow the solution 1 (popup with settings for category Notes from Clipboard)? Seems like some visual issue but I do not understand how it looks on your device.

**Comment by coachsequoia** [comment]
Hi.
Here are 2 screenshots:
[image: image.png]
then after clicking the 3 lines on the right edge:
[image: image.png]
then after clicking Empty: [nothing gets emptied]
[image: image.png]
Am I doing something wrong?
This is a Pixelbook Chromebook by Google.
Thanks.

*sequoia*
*Sequoia Lundy*


*Vancouver:   778-822-4408 toll-free:       877-822-0844US:
 360-436-6444Zoom:           778-822-4408 *

**Comment by atrashler** [comment]
Sorry, you have not attached the screenshots:)

**Comment by coachsequoia** [comment]
Hi again,
Here is my earlier email again. It contains 3 screenshots in png format. I
hope you get them this time :}

*sequoia*
*Sequoia Lundy*


*Vancouver:   778-822-4408 toll-free:       877-822-0844US:
 360-436-6444Zoom:           778-822-4408 *


---------- Forwarded message ---------
From: Coach Sequoia <coach.sequoia@gmail.com>
Date: Sat, Feb 6, 2021 at 11:36 AM
Subject: Re: [clipto-pro/Android] missing "Clear" button on phone app (#48)
To: clipto-pro/Android <
reply@reply.github.com>
Cc: clipto-pro/Android <Android@noreply.github.com>, Author <
author@noreply.github.com>


Hi.
Here are 3 screenshots:
[image: image.png]
then after clicking the 3 lines on the right edge:
[image: image.png]
then after clicking Empty: [nothing gets emptied]
[image: image.png]
Am I doing something wrong?
This is a Pixelbook Chromebook by Google.
Thanks.

*sequoia*
*Sequoia Lundy*


*Vancouver:   778-822-4408 toll-free:       877-822-0844US:
 360-436-6444Zoom:           778-822-4408 *
