### ISSUE TITLE
Login and Sync

### ISSUE THREAD

**Issue by Unifreelance** [clipto-pro/Android#49]
Cannot log in from my back-up Android phone. When I try, nothing happens and I am just returned to the settings menu. Any advice would be appreciated. Br. UFL.

**Comment by atrashler** [comment]
1) Could you write what auth type do you use on your backup device?
2) Could you try to sign in on this device with “long-click” on sign in button?

**Comment by Unifreelance** [comment]
Hi Alex,

Sorry, I forgot to say, that I login using Google.

Anyway, long-click sign in worked fine. Now logged in and synced.

Thanks for responding quickly.

BR
Leif


lør. 1. aug. 2020 20.44 skrev Alex Trashler <notifications@github.com>:

**Comment by atrashler** [comment]
Seems like your device experience problems with Google Play Services. The flow with “long-click” is trying to bypass it and uses our site to create authorization token.

**Comment by Unifreelance** [comment]
Hi Alex,

Just checked Google Pay, everything looked normal, same with Google Play,
not sure what might be the problem.

By thanks for helping me getting signed in, anyway.

Br Leif

lør. 1. aug. 2020 21.46 skrev Alex Trashler <notifications@github.com>:
