### ISSUE TITLE
Clipto doesn't want to delete the previously Copied texts anymore...

### ISSUE THREAD

**Issue by budikesuma** [clipto-pro/Android#51]
clipto doesn't want to delete the previously copied texts.  Since Clipto deleted it, but the texts immediately appeared again, I have tried dozens of times, I even deleted hundreds of texts but then appeared again.  Also the bottom texts why is it not set to be deleted automatically?  Now Clipto can't copy text anymore, maybe because the stored text is full? (Thousands of texts already)

**Comment by atrashler** [comment]
Could you please write the app version? It can be found at the bottom of Settings screen.

**Comment by atrashler** [comment]
Please upgrade to the latest version. I have updated security rules few months ago and old versions are not allowed to sync data with the cloud. The latest version should be 4.1.x or later.
Thanks!
