### ISSUE TITLE
Context-menu item

### ISSUE THREAD

**Issue by toddwc** [clipto-pro/Android#56]
Please consider making the context-menu item an option.

It requires users to move cursor more to select top items. And I haven't found any use for the context-menu item. For example, I can already search Google from the same context menu.

(It could be useful by adding some text-manipulation functions, similar to what Notepad++ can do.)

Thank you.

**Comment by toddwc** [comment]
(Oops. That should have been posted in desktop area.)

**Comment by atrashler** [comment]
I will check how it works in Notepad++.
I want to do something similar but need examples what can be useful:)
