### ISSUE TITLE
1-click copy in Android 10

### ISSUE THREAD

**Issue by DashWatson** [clipto-pro/Android#6]
In Android 10, when I select text, I have to press the expand context menu button, then click "Clipto...", then click copy in the Clipto dialog box to actually get it copied. That's 3 taps, can you make it an option for people to make it a bit easier? In the app settings, you can give the user the option to keep either the "Clipto..." dialog box button or just a 1-click copy button (convenient) or both (might get crowded).
Most of the time, I just want to get some text copied and then keep writing or finish what I'm doing. I appreciate Clipto offering so many intelligent ways to handle the text copied in the "Clipto..." dialog box, but I don't want it every time. It would be really nice to have an option to 1 click-copy to Clipto from there even in Android 10 like the system copy button does in all previous versions of Android. A button that just copies the text to Clipto without offering any special actions like the "Clipto..." button does.

**Comment by atrashler** [comment]
Good idea with configured behaviour for 'Clipto...' action. The initial idea was like you have described so I think it is possible to implement such behaviour and make it configurable.

Thanks!

The only one limitation - 'Clipto...' action will still be 2-click (you expand context menu first and then click 'Clipto...' because this behaviour we can not change)

**Comment by DashWatson** [comment]
I found this resolved in the recent update. Thanks a lot!

**Comment by atrashler** [comment]
Yes. It should work now. Please check if it useful or not, probably it can be improved..

**Comment by atrashler** [comment]
More advanced and almost the same functionality as prior Android 10 will be implemented in this request #11
