### ISSUE TITLE
settings page

### ISSUE THREAD

**Issue by toddwc** [clipto-pro/Android#63]
I had to reset my Chromebook. When I was done, I opened clipto to make sure it was syncing. I couldn't find the settings, just a lot of badges called "rune" something. I thought the app had been hacked.

Why would you ruin an app with this silliness? I don't have the patience to click each one and figure out what they do. Sorry to say, despite my $25 in donations, I'll be looking for a new clipboard app.

Good luck.

**Comment by atrashler** [comment]
The old screen is available if you “long click” on the Settings action in the left navigation panel. But it is too boring and does not give the understanding of the functionality of the app:(

**Comment by toddwc** [comment]
For a utility app, boring is good.
