### ISSUE TITLE
[BUG]: Import von Notizen über Takeout.zip ergibt stets 0 importierte Einträge

### ISSUE THREAD

**Issue by Benko111** [clipto-pro/Android#73]
Wenn versucht wird aus der Google-Notizen-App die hundertfach gespeicherten Notizen via Google-Takeout.zip zu importieren, wird der Vorgang jedesmal mit der Meldung "Erfolg: 0 Notizen importiert" abgeschlossen. Anscheinend wird die Zip-Datei überhaupt nicht geparsed. Ein Screenshot der Meldung liegt bei. Clip To-Version: 5.5.16; Android 11 LineageOS auf Samsung 10.
![Screenshot_20210407-023636_Clipto](https://user-images.githubusercontent.com/10970002/113796756-46723600-9750-11eb-9065-cecbcab5320d.png)
`

**Comment by atrashler** [comment]
Which version of the app?

**Comment by Benko111** [comment]
As I wrote above: 5.5.16

**Comment by atrashler** [comment]
Sorry, did not see it. I will check it. If it is possible, could you make any export with one or few “test notes” so I can reproduce it. Probably some language specific issue that the app can not proceed correctly. On my devices it works, but seems like my backups does not contain some specific logic that could lead to the issue. If it is not possible, I will check it anyway. Thanks!

**Comment by Benko111** [comment]
No problem, will do so later on after dinner. Thanks for your efforts.

**Comment by Benko111** [comment]
Well, turns out I cannot select what notes to include or to exclude, only can choose to include notes in general in the Takeout.zip. So I'd need to use another account to create test-notes. If you pass me your email I'll send you my original Takeout.zip - nothing too private in there.

**Comment by atrashler** [comment]
> Well, turns out I cannot select what notes to include or to exclude, only can choose to include notes in general in the Takeout.zip. So I'd need to use another account to create test-notes. If you pass me your email I'll send you my original Takeout.zip - nothing too private in there.

clipto.pro@gmail.com
