### ISSUE TITLE
Confusing settings panel 

### ISSUE THREAD

**Issue by Abragus** [clipto-pro/Android#75]
This has been mentioned before, specifically in #63 . The settings panel is just confusing. In that post, it was argued that the Runes would make the settings less boring than a normal settings panel, and that the old one wouldn't give a good understanding of the functuality of the app. I agree, the runes are a bit less boring, if that was ever seen as a problem in a settings panel. But much more importantly, they are incredibly hard to understand. 

"Astral Sync", "Iron Shield", "Chameleon Skin", "The Oculus", "Blowing Copy", "Swipe Power", "Point of No Return", "Shifted Focus", and "Revive" are all Runes. 

How am I supposed to understand what any of these do? I would _maybe_ be able to guess a few of them without clicking to read more, but most of them just feel like magical sounding nonsense. I would consider renamning them to something more traditional like: 

"Cloud Sync", "Password Protection", "Themes", "Link Previews", "Hide After Copy", "Swipe Actions", "Auto Save Edits", "Auto Focus on Title", and "Restore Session" 

And I totally understand that this would remove the "magical" aspect of the page, but for a settings page, functionality should definitely come first, and with names like these, that just isn't the case. The icons and the layout is okay (actually, I kinda like the whole "Rune" idea in itself), as long as I am able to quickly understand what the setting does, just by reading the title. After all, this is a clipboard app, not an RPG set in a magical medival world. 

Also, as a translator, these runes (and the name "Rune" itself) is incredibly difficult to translate properly. The words just don't have the same feel in my own language as in English, instead just sounding silly. But anyway, I digress.

**Comment by atrashler** [comment]
I don't insist on an exact translation:) Probably later I will change the default translations as you have mentioned. The only limitation for the names of the 'runes' is to make it as short as possible (actually, your translations are perfect in terms of the length and the meaning).
The term 'Rune' and 'Skill Rune' can also be translated to something like 'Feature' or 'Modification' or something similar and more obvious.

Crowdin page is opened for everyone and you can translate the app however you like (just don't add swear words;)

**Comment by Abragus** [comment]
Yeah, that is what I was thinking of doing. Good to know that you are considering changing the names! That would be a great move, in my opinion.

**Comment by okaloben** [comment]
I can't find the option to pin starred notes.Was it removed?

**Comment by atrashler** [comment]
> I can't find the option to pin starred notes.Was it removed?

It was temporary moved to the specific settings of category 'Starred':

1)  Long click on the category Starred

OR

1) Select category Starred
2) Click on 'three dots menu' in the main list

In the opened dialog you can find the setting 'Pin Starred Notes'. I have moved it to the settings of specific category, due to necessary to sync this settings across devices. Probably later it will be more obvious to access this setting:-)

**Comment by okaloben** [comment]
Thanks alot
