### ISSUE TITLE
Cannot pin starred notes to the top

### ISSUE THREAD

**Issue by anti-pencil** [clipto-pro/Android#76]
I used to have my starred notes configured to be displayed/pinned at the top. Now the option seems to have disappeared from the mobile app. This feature still works on 4.7.3 version on Linux.

**Comment by atrashler** [comment]
> I used to have my starred notes configured to be displayed/pinned at the top. Now the option seems to have disappeared from the mobile app. This feature still works on 4.7.3 version on Linux.

Now this setting is temporary (or not) moved to the specific settings of category Starred:

1) click on “three dots” action on Starred category
2) activate “Pin Starred Notes”
3) this setting should be synced across all your devices starting from version 5.x
