### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by klorinczi** [clipto-pro/Android#77]
Could be possible to change language?

**Comment by atrashler** [comment]
> Could be possible to change language?

On Android the language is defined by the system. Probably I could add an option as on Desktop to change the language within the app.

**Comment by klorinczi** [comment]
I can't believe, that language could not be changed on Android optionally...

**Comment by atrashler** [comment]
> I can't believe, that language could not be changed on Android optionally...

It can be. I just wrote that in the latest version it is not possible and need to be implemented:-)

**Comment by atrashler** [comment]
implemented in v6.0.4

**Comment by klorinczi** [comment]
Thank you!
