### ISSUE TITLE
Monitor clipboard in background with ADB

### ISSUE THREAD

**Issue by pota2dev** [clipto-pro/Android#79]
Is this possible to copy content from clipboard in background using ADB commands(non-root) without opening the app?

**Comment by atrashler** [comment]
> Is this possible to copy content from clipboard in background using ADB commands(non-root) without opening the app?

yes. the app has in-app instructions how to do it, when you activate the setting “Notes from Clipboard”

**Comment by Mahdi-Noor-Hasan** [comment]
Can't find instructions in the latest version(5.6.3-release) of the app.

**Comment by pota2dev** [comment]
> > Is this possible to copy content from clipboard in background using ADB commands(non-root) without opening the app?
> 
> yes. the app has in-app instructions how to do it, when you activate the setting “Notes from Clipboard”

Can't find instructions in the latest version(5.6.3-release) of the app after enabling “Notes from Clipboard".

And does it still require the app to run in background to monitor clipboard?

**Comment by atrashler** [comment]
> > > Is this possible to copy content from clipboard in background using ADB commands(non-root) without opening the app?
> > 
> > 
> > yes. the app has in-app instructions how to do it, when you activate the setting “Notes from Clipboard”
> 
> Can't find instructions in the latest version(5.6.3-release) of the app after enabling “Notes from Clipboard".
> 
> And does it still require the app to run in background to monitor clipboard?

The instruction: https://clipto.pro/l/KanLCodapScXwxAy7

Yes. It is required to run the app in the background.
