### ISSUE TITLE
Filter: allow logical operators in search text

### ISSUE THREAD

**Issue by aisbergde** [clipto-pro/Android#8]
For example when I want to search all notes containing ♂ or ♀ such kind of logical operator would be helpful.

**Comment by atrashler** [comment]
good idea. Have added to the backlog.

**Comment by atrashler** [comment]
In the latest version 2.35.11 it is possible to use comma to find all notes with 'or logic'.
Please check it.

**Comment by aisbergde** [comment]
it worksfine. The feature should be added to the FAQ to enable users to find.

**Comment by atrashler** [comment]
Yes. FAQ will be updated in the next release. Thanks!
