### ISSUE TITLE
This could be a way

### ISSUE THREAD

**Issue by LastGuardianAngel** [clipto-pro/Android#90]
Does it mean that the required fonts can not be found here - https://fonts.google.com?

I looked it up but, I don't understand how one could import the font's. There should be a way to do it. Maybe have the text in the font you want from somewhere else, then copied and pasted in clipto. That could work.

**Comment by atrashler** [comment]
> Does it mean that the required fonts can not be found here - https://fonts.google.com?
> 
> I looked it up but, I don't understand how one could import the font's. There should be a way to do it. Maybe have the text in the font you want from somewhere else, then copied and pasted in clipto. That could work.

I do not understand the question:) The current logic (and actually the standard logic) is that the app uses “downloadable fonts api” from Google, which uses fonts.google.com under the hood. In such a way it is possible to use any number of fonts in the app and do not impact its size.
However, the app must declare in its manifest that it is going to use these fonts. It means, that each time I want to add support of a new font, I need to add it to the app manifest and publish a new version, so the new font can be available in the new version.
