### ISSUE TITLE
notes made in browser on PC are not synced with mobile

### ISSUE THREAD

**Issue by igorzhilin** [clipto-pro/Android#91]
I created notes in PC browser, Firefox. I also created a new tag for those notes via PC browser. The notes have been saved and I can see them from PC browser. I can also see them from a different PC.

However, they do not appear in my mobile!

The newly created tag has been synced with mobile. However, not the notes. The note count for this tag on PC shows the right count. The note count for the same tag on mobile shows 0.

Notes made from mobile still work. They are visible both in mobile and in PC browser.

I have still plenty of available notes left in my plan.
I tried to stop and start "Sync notes automatically" on PC and mobile, but it didn't help.
I tried to disable uBlock in PC Firefox, also didn't help.

**Comment by atrashler** [comment]
> I created notes in PC browser, Firefox. I also created a new tag for those notes via PC browser. The notes have been saved and I can see them from PC browser. I can also see them from a different PC.
> 
> However, they do not appear in my mobile!
> 
> The newly created tag has been synced with mobile. However, not the notes. The note count for this tag on PC shows the right count. The note count for the same tag on mobile shows 0.
> 
> Notes made from mobile still work. They are visible both in mobile and in PC browser.
> 
> I have still plenty of available notes left in my plan. I tried to stop and start "Sync notes automatically" on PC and mobile, but it didn't help. I tried to disable uBlock in PC Firefox, also didn't help.

Could you please send me:
1) the version of the mobile app
2) your account uid (Settings -> Astral Sync -> user uid field)

**Comment by igorzhilin** [comment]
1. 7.1.14-release
2. QnTF8Ld5j9TfYNy2FY3iwoTtdZK2

**Comment by atrashler** [comment]
> * 7.1.14-release
> * QnTF8Ld5j9TfYNy2FY3iwoTtdZK2

Could you sign out the mobile app and sign in it again? Will the number of notes be the same as in the browser?

**Comment by igorzhilin** [comment]
This worked, thank you. Now I see those PC notes. I'll see if the issue reoccurrs.
