### ISSUE TITLE
copy causes its deletion

### ISSUE THREAD

**Issue by franco27** [clipto-pro/Android#94]
Hello. 

I would like to report a bug to you.

 After a search, in clipto, when I click on the note to copy to the clipboard.
 this note is then deleted. the copy causes its deletion. 

I can repeat this problem. These notes have labels

**Comment by atrashler** [comment]
> Hello.
> 
> I would like to report a bug to you.
> 
> After a search, in clipto, when I click on the note to copy to the clipboard. this note is then deleted. the copy causes its deletion.
> 
> I can repeat this problem. These notes have labels

Could you please:

1) check the version of the app
2) sign out and sign in the app again (the local index need to be updated in order to apply some internal changes)
3) copy any note again
4) let me know once you have done

Thanks!

**Comment by franco27** [comment]
Thank you for your reply.
 I did what you told me. I logged out and logged in again. 

this problem is solved. Thank you

**Comment by franco27** [comment]
to prevent this problem from happening again, do you advise me after each update to disconnect and reconnect?

**Comment by atrashler** [comment]
> to prevent this problem from happening again, do you advise me after each update to disconnect and reconnect?

No. It was one time action. Usually I wrote about it in 'What's new'. But if something similar happens in the future, you know the universal solution: 'Sign out and sign in again':)
